## TENSORS: REDO
> a `tensor` gives you a format of shaping your data for feeding it as input to your neural net

the journey of building a neural network begins with data. before you can design a model or start the training process, you must gather your information and prepare it in a format the model can understand. in pytorch, that fundamental format is the **tensor**. tnsors are more than just data containers; they are optimized for the mathematical operations that power deep learning.

regardless of how efficient tensors are some common errors encountered when building models are related to tensor shapes, types, or dimensions. so you can do tensor manipulation, as well as debug issues when you encounter these errors.

#### context:

* create tensors from different data sources such as python lists and numpy arrays.

* reshape and manipulate tensor dimensions to prepare data for model inputs.

* use indexing and slicing techniques to access and filter specific parts of your data.

* perform the mathematical and logical operations that form the basis of all neural network computations.


In [1]:
import torch
import numpy as np
import pandas as pd

## 1 - tensor creation

the goal is to get your data ready for the model i.e. loading your data into tensors. and you could do that in multiple ways conveniently: 

### 1.1 from existing data structures - vanilla python:

e.g python list, a numpy array, or a pandas dataframe. w/ pytorch you get straightforward functions to convert these structures into tensors, making the data preparation stage more efficient.

* `torch.tensor()`: this function takes input such as a python list to convert it into a tensor.

**NOTE:** for the type of numbers eg use of integers, pytorch stores them as integers. if you include decimals, they'll be stored as floating point values.

In [2]:
x = torch.tensor([1, 2, 3])

print("FROM PYTHON LISTS:", x)
print("TENSOR DATA TYPE:", x.dtype)

FROM PYTHON LISTS: tensor([1, 2, 3])
TENSOR DATA TYPE: torch.int64


In [3]:
#print shape
print("TENSOR DATA SHAPE:", x.shape)

TENSOR DATA SHAPE: torch.Size([3])


<br>

* `torch.from_numpy()`: converts a numpy array into a pytorch tensor.

In [4]:
# numpy array
numpy_array = np.array([[1, 2, 3], [4, 5, 6]])
torch_tensor_from_numpy = torch.from_numpy(numpy_array)

print("TENSOR FROM NUMPY:\n\n", torch_tensor_from_numpy)

TENSOR FROM NUMPY:

 tensor([[1, 2, 3],
        [4, 5, 6]])


In [6]:
print("shape: ", torch_tensor_from_numpy.shape)

shape:  torch.Size([2, 3])


> dataframe stores tabular data in rows + columns

<br>  

- ### *from a `pandas` dataframe*:
pandas is a python library for working with data organized in rows and columns, like a csv file or spreadsheet. A dataframe is pandas' **data structure** for storing this kind of tabular data. dataframes are one of the most common ways to load datasets in ml, especially when reading csv files. there is not a direct function to convert a dataframe to a tensor. the standard method is to extract the data from the dataframe into a numpy array using the `.values` attribute, and then convert that array into a tensor using `torch.tensor()`.

In [7]:
DF = pd.read_csv('./data.csv')
DF.head(5)

,distance_miles,delivery_time_minutes
0,1.60,7.22
1,13.09,32.41
2,6.97,17.47


In [8]:
# read the data from the csv file into a dataframe
df = pd.read_csv('./data.csv')

# extract the data as a numpy array from the dataframe
all_values = df.values

# convert the dataframe's values to a tensor
tensor_from_df = torch.tensor(all_values)

print("ORIGINAL DATAFRAME:\n\n", df)
print("\nRESULTING TENSOR:\n\n", tensor_from_df)
print("\nTENSOR DATA TYPE:", tensor_from_df.dtype)

ORIGINAL DATAFRAME:

    distance_miles  delivery_time_minutes
0            1.60                   7.22
1           13.09                  32.41
2            6.97                  17.47

RESULTING TENSOR:

 tensor([[ 1.6000,  7.2200],
        [13.0900, 32.4100],
        [ 6.9700, 17.4700]], dtype=torch.float64)

TENSOR DATA TYPE: torch.float64


### 1.2 - w/ predefined values:

this is meant for when you need to create tensors for specific purposes, eg initializing a model's weights and biases before training begins. pytorch allows you to quickly generate tensors filled with placeholder values like zeros, ones, or random numbers, which is useful for testing and setup.

* `torch.zeros()`: creates a tensor filled with zeros of the specified dimensions.

In [9]:
zeros = torch.zeros(2, 3)

print("TENSOR WITH ZEROS:\n\n", zeros)

TENSOR WITH ZEROS:

 tensor([[0., 0., 0.],
        [0., 0., 0.]])


<br>

* `torch.ones()`: creates a tensor filled with ones of the specified dimensions.

In [10]:
ones = torch.ones(2, 3)

print("TENSOR WITH ONES:\n\n", ones)

TENSOR WITH ONES:

 tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [13]:
tensor = torch.ones(2, 3)
ones = torch.ones_like(tensor)
zeros = torch.zeros_like(tensor)
print("ones tensor with same shape:\n\n", ones)
print("zeros tensor with same shape:\n\n", zeros)


ones tensor with same shape:

 tensor([[1., 1., 1.],
        [1., 1., 1.]])
zeros tensor with same shape:

 tensor([[0., 0., 0.],
        [0., 0., 0.]])


<br>
INFO: 

* `torch.rand()`: generates a tensor with random numbers uniformly distributed between 0 and 1, based on the specified dimensions.

In [14]:
# random numbers
random = torch.rand(2, 3)

print("RANDOM TENSOR:\n\n", random)

RANDOM TENSOR:

 tensor([[0.9005, 0.6940, 0.6114],
        [0.2610, 0.4182, 0.2641]])


### 1.3 - from a sequence

if you need to generate a sequence of data points, such as a range of values for testing a model's predictions, you can create a tensor directly from that sequence.

* `torch.arange()`: creates a 1D tensor containing a range of numbers from the specified start value to one less than the specified stop value, incrementing (if positive) or decrementing (if negative) by the specified `step` value.

In [15]:
range_tensor = torch.arange(0, 10, step=1)

print("ARANGE TENSOR:", range_tensor)

ARANGE TENSOR: tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


## 2 - reshaping & manipulating

a common source of errors in pytorch models is a mismatch between the shape of your input data and the shape your model expects; such as a model typically designed to process a batch of data, so even if you want to make a single prediction, you must shape your input tensor to look like a batch of one.

### 2.1 - checking a tensor's dimensions:

fixing a shape mismatch nees you to understand the current dimensions of your tensor. it tells you how many samples you have and how many features are in each sample.

* `torch.Tensor.shape`: an attribute that returns a `torch.Size` object detailing the size of the tensor along each dimension.

In [16]:
# a 2D tensor
x = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])

print("ORIGINAL TENSOR:\n\n", x)
print("\nTENSOR SHAPE:", x.shape)

ORIGINAL TENSOR:

 tensor([[1, 2, 3],
        [4, 5, 6]])

TENSOR SHAPE: torch.Size([2, 3])


### 2.2 - changing a tensor's dimensions:

once you identify a shape mismatch, you need to correct it; e.g. adding a dimension to a single data sample to create a batch of size one for your model, or removing a dimension after a batch operation is complete.

* **adding dimension:** `torch.Tensor.unsqueeze()` inserts a new dimension at the specified index.
    * *NOTE: the shape will change from `[2, 3]` to `[1, 2, 3]` and the tensor gets wrapped in an extra pair of square brackets `[]`*.

In [17]:
print("ORIGINAL TENSOR:\n\n", x)
print("\nTENSOR SHAPE:", x.shape)
print("-"*45)

# dimension
expanded = x.unsqueeze(0)  # add dimension at index 0

print("\nTENSOR WITH ADDED DIMENSION AT INDEX 0:\n\n", expanded)
print("\nTENSOR SHAPE:", expanded.shape)

ORIGINAL TENSOR:

 tensor([[1, 2, 3],
        [4, 5, 6]])

TENSOR SHAPE: torch.Size([2, 3])
---------------------------------------------

TENSOR WITH ADDED DIMENSION AT INDEX 0:

 tensor([[[1, 2, 3],
         [4, 5, 6]]])

TENSOR SHAPE: torch.Size([1, 2, 3])


<br>

* **removing dimension:** `torch.Tensor.squeeze()` removes dimensions of size 1.
    * *NOTE: This reverses the unsqueeze operation, removing the `1` from the shape and taking away a pair of outer square brackets*.

In [19]:
print("EXPANDED TENSOR:\n\n", expanded)
print("\nTENSOR SHAPE:", expanded.shape)
print("-"*36)

# remove dimension
squeezed = expanded.squeeze()

print("\nTENSOR WITH DIMENSION REMOVED:\n\n", squeezed)
print("\nTENSOR SHAPE:", squeezed.shape)

EXPANDED TENSOR:

 tensor([[[1, 2, 3],
         [4, 5, 6]]])

TENSOR SHAPE: torch.Size([1, 2, 3])
------------------------------------

TENSOR WITH DIMENSION REMOVED:

 tensor([[1, 2, 3],
        [4, 5, 6]])

TENSOR SHAPE: torch.Size([2, 3])


### 2.3 - restructuring

beyond adding or removing dimensions, you can change a tensor's structure to match the requirements of a specific layer or operation within your neural network.

* **RESHAPING:** `torch.Tensor.reshape()` changes the shape of a tensor to the specified dimensions.

In [22]:
print("ORIGINAL TENSOR:\n\n", x)
print("\nTENSOR SHAPE:", x.shape)
print("-"*32)

# reshape
reshaped = x.reshape(3, 2)

print("\nAFTER PERFORMING reshape(3, 2):\n\n", reshaped)
print("\nTENSOR SHAPE:", reshaped.shape)

ORIGINAL TENSOR:

 tensor([[1, 2, 3],
        [4, 5, 6]])

TENSOR SHAPE: torch.Size([2, 3])
--------------------------------

AFTER PERFORMING reshape(3, 2):

 tensor([[1, 2],
        [3, 4],
        [5, 6]])

TENSOR SHAPE: torch.Size([3, 2])


* **TRANSPOSING:** `torch.Tensor.transpose()` swaps the specified dimensions of a tensor.

In [23]:
print("ORIGINAL TENSOR:\n\n", x)
print("\nTENSOR SHAPE:", x.shape)
print("-"*32)

# transpose
transposed = x.transpose(0, 1)

print("\nAFTER PERFORMING transpose(0, 1):\n\n", transposed)
print("\nTENSOR SHAPE:", transposed.shape)

ORIGINAL TENSOR:

 tensor([[1, 2, 3],
        [4, 5, 6]])

TENSOR SHAPE: torch.Size([2, 3])
--------------------------------

AFTER PERFORMING transpose(0, 1):

 tensor([[1, 4],
        [2, 5],
        [3, 6]])

TENSOR SHAPE: torch.Size([3, 2])


### 2.4 - combining tensors

you might need to combine data from different sources or merge separate batches into one larger dataset.

* `torch.cat()`: enables you to join a sequence of tensors along an existing dimension.
* NOTE: all tensors must have the same shape in dimensions other than the one being concatenated.

In [25]:
# create two tensors to concatenate
tensor_a = torch.tensor([[1, 2],
                         [3, 4]])
tensor_b = torch.tensor([[5, 6],
                         [7, 8]])

# concatenate along columns (dim=1)
concatenated_tensors = torch.cat((tensor_a, tensor_b), dim=1)


print("TENSOR A:\n\n", tensor_a)
print("\nTENSOR B:\n\n", tensor_b)
print("-"*28)
print("\nCONCATENATED TENSOR (dim=1):\n\n", concatenated_tensors)

TENSOR A:

 tensor([[1, 2],
        [3, 4]])

TENSOR B:

 tensor([[5, 6],
        [7, 8]])
----------------------------

CONCATENATED TENSOR (dim=1):

 tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])


## 3 - indexing & slicing

after you have your data in a tensor, you will often need to access specific parts of it. whether you are grabbing a single prediction to inspect its value, separating your input features from your labels, or selecting a subset of data for analysis, indexing and slicing are the tools for the job.

### 3.1 - retrieving elements

these are techniques for getting data out of a tensor, working very similarly to how you would access elements in a standard python list.

* **standard indexing**: accessing single elements or entire rows using integer indices (e.g., `x[0]`, `x[1, 2]`).

In [26]:
# create a 3x4 tensor
x = torch.tensor([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])
print("ORIGINAL TENSOR:\n\n", x)
print("-" * 55)

# get a single element at row 1, column 2
single_element_tensor = x[1, 2]

print("\nINDEXING SINGLE ELEMENT AT [1, 2]:", single_element_tensor)
print("-" * 55)

# get the entire second row (index 1)
second_row = x[1]

print("\nINDEXING ENTIRE ROW [1]:", second_row)
print("-" * 55)

# last row
last_row = x[-1]

print("\nINDEXING ENTIRE LAST ROW ([-1]):", last_row, "\n")

ORIGINAL TENSOR:

 tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
-------------------------------------------------------

INDEXING SINGLE ELEMENT AT [1, 2]: tensor(7)
-------------------------------------------------------

INDEXING ENTIRE ROW [1]: tensor([5, 6, 7, 8])
-------------------------------------------------------

INDEXING ENTIRE LAST ROW ([-1]): tensor([ 9, 10, 11, 12]) 



<br>

* **slicing**: extracting sub-tensors using `[start:end:step]` notation (e.g., `x[:2, ::2]`).
    * *NOTE: The `end` index itself is not included in the slice.*
* slicing can be used to access entire columns.

In [27]:
print("ORIGINAL TENSOR:\n\n", x)
print("-" * 55)

# get the first two rows
first_two_rows = x[0:2]

print("\nSLICING FIRST TWO ROWS ([0:2]):\n\n", first_two_rows)
print("-" * 55)

# get the third column of all rows
third_column = x[:, 2]

print("\nSLICING THIRD COLUMN ([:, 2]]):", third_column)
print("-" * 55)

# every other column
every_other_col = x[:, ::2]

print("\nEVERY OTHER COLUMN ([:, ::2]):\n\n", every_other_col)
print("-" * 55)

# last column
last_col = x[:, -1]

print("\nLAST COLUMN ([:, -1]):", last_col, "\n")

ORIGINAL TENSOR:

 tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
-------------------------------------------------------

SLICING FIRST TWO ROWS ([0:2]):

 tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
-------------------------------------------------------

SLICING THIRD COLUMN ([:, 2]]): tensor([ 3,  7, 11])
-------------------------------------------------------

EVERY OTHER COLUMN ([:, ::2]):

 tensor([[ 1,  3],
        [ 5,  7],
        [ 9, 11]])
-------------------------------------------------------

LAST COLUMN ([:, -1]): tensor([ 4,  8, 12]) 



* ### combining indexing & slicing:

In [31]:
print("ORIGINAL TENSOR:\n\n", x)
print("-" * 42)

# combining slicing and indexing (first two rows, last two columns)
combined = x[0:2, 2:]

print("\nFIRST TWO ROWS, LAST TWO COLS ([0:2, 2:]):\n\n", combined, "\n")

ORIGINAL TENSOR:

 tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
------------------------------------------

FIRST TWO ROWS, LAST TWO COLS ([0:2, 2:]):

 tensor([[3, 4],
        [7, 8]]) 



<br>

* **`.item()`**: extracts the value from a single-element tensor as a standard python number.

In [32]:
print("SINGLE-ELEMENT TENSOR:", single_element_tensor)
print("-" * 32)

# extract the value from a single-element tensor as a standard Python number
value = single_element_tensor.item()

print("\n.item() PYTHON NUMBER EXTRACTED:", value)
print("TYPE:", type(value))

SINGLE-ELEMENT TENSOR: tensor(7)
--------------------------------

.item() PYTHON NUMBER EXTRACTED: 7
TYPE: <class 'int'>


### 3.2 - advanced indexing:

for more complex data selection, such as filtering your dataset based on one or more conditions, you can use advanced indexing techniques.

* **boolean masking**: using a boolean tensor to select elements that meet a certain condition (e.g., `x[x > 5]`).

In [33]:
print("ORIGINAL TENSOR:\n\n", x)
print("-" * 55)

# boolean indexing using logical comparisons
mask = x > 6

print("MASK (VALUES > 6):\n\n", mask, "\n")

# spplying Boolean masking
mask_applied = x[mask]

print("VALUES AFTER APPLYING MASK:", mask_applied, "\n")

ORIGINAL TENSOR:

 tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
-------------------------------------------------------
MASK (VALUES > 6):

 tensor([[False, False, False, False],
        [False, False,  True,  True],
        [ True,  True,  True,  True]]) 

VALUES AFTER APPLYING MASK: tensor([ 7,  8,  9, 10, 11, 12]) 



<br>

* **fancy indexing**: using a tensor of indices to select specific elements in a non-contiguous way.

In [34]:
print("ORIGINAL TENSOR:\n\n", x)
print("-" * 55)

# fancy indexing

# get first and third rows
row_indices = torch.tensor([0, 2])

# get second and fourth columns
col_indices = torch.tensor([1, 3]) 

# gets values at (0,1), (0,3), (2,1), (2,3)
get_values = x[row_indices[:, None], col_indices]

print("\nSPECIFIC ELEMENTS USING INDICES:\n\n", get_values, "\n")

ORIGINAL TENSOR:

 tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
-------------------------------------------------------

SPECIFIC ELEMENTS USING INDICES:

 tensor([[ 2,  4],
        [10, 12]]) 



## 4 - mathematical & logical operations

at their core, neural networks are performing mathematical computations. a single neuron, for example, calculates a weighted sum of its inputs and adds a bias. pytorch is optimized to perform these operations efficiently across entire tensors at once, which is what makes training so fast.

### 4.1 - arithmetic:

pytorch handles element-wise calculations and uses a powerful feature called broadcasting to simplify your code.

* **element-wise operations**: standard math operators (`+`, `*`) that apply to each element independently.

In [36]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])
print("TENSOR A:", a)
print("TENSOR B", b)
print("-" * 56)

# element-wise addition
sum_tensor = a + b

print("\nAFTER PERFORMING ELEMENT-WISE ADDITION:", sum_tensor, "\n")

TENSOR A: tensor([1, 2, 3])
TENSOR B tensor([4, 5, 6])
--------------------------------------------------------

AFTER PERFORMING ELEMENT-WISE ADDITION: tensor([5, 7, 9]) 



In [37]:
print("TENSOR A:", a)
print("TENSOR B", b)
print("-" * 65)

# element-wise multiplication
product_tensor = a * b

print("\nAFTER PERFORMING ELEMENT-WISE MULTIPLICATION:", product_tensor, "\n")

TENSOR A: tensor([1, 2, 3])
TENSOR B tensor([4, 5, 6])
-----------------------------------------------------------------

AFTER PERFORMING ELEMENT-WISE MULTIPLICATION: tensor([ 4, 10, 18]) 



<br>

#### dot product:
* **`torch.matmul()`**: computes the dot product of two vectors or matrices.

In [38]:
print("TENSOR A:", a)
print("TENSOR B", b)
print("-" * 65)

# dot product
dot_product = torch.matmul(a, b)

print("\nAFTER PERFORMING DOT PRODUCT:", dot_product, "\n")

TENSOR A: tensor([1, 2, 3])
TENSOR B tensor([4, 5, 6])
-----------------------------------------------------------------

AFTER PERFORMING DOT PRODUCT: tensor(32) 



<br>

* **BROADCASTING**: the automatic expansion of smaller tensors to match the shape of larger tensors during arithmetic operations.
    * broadcasting allows operations between tensors with compatible shapes, even if they don't have the exact same dimensions.

In [39]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([[1],
                 [2],
                 [3]])

print("TENSOR A:", a)
print("SHAPE:", a.shape)
print("\nTENSOR B\n\n", b)
print("\nSHAPE:", b.shape)
print("-" * 65)

# apply broadcasting
c = a + b


print("\nTENSOR C:\n\n", c)
print("\nSHAPE:", c.shape, "\n")

TENSOR A: tensor([1, 2, 3])
SHAPE: torch.Size([3])

TENSOR B

 tensor([[1],
        [2],
        [3]])

SHAPE: torch.Size([3, 1])
-----------------------------------------------------------------

TENSOR C:

 tensor([[2, 3, 4],
        [3, 4, 5],
        [4, 5, 6]])

SHAPE: torch.Size([3, 3]) 



### 4.2 - logic & comparisons

logical operations are powerful tools for data preparation and analysis. they allow you to create boolean masks to filter, select, or modify your data based on specific conditions you define.

* **comparison operators**: element-wise comparisons (`>`, `==`, `<`) that produce a boolean tensor.

In [40]:
temperatures = torch.tensor([20, 35, 19, 35, 42])
print("TEMPERATURES:", temperatures)
print("-" * 50)

### comparison Operators (>, <, ==)

# use '>' (greater than) to find temperatures above 30
is_hot = temperatures > 30

# use '<=' (less than or equal to) to find temperatures 20 or below
is_cool = temperatures <= 20

# use '==' (equal to) to find temperatures exactly equal to 35
is_35_degrees = temperatures == 35

print("\nHOT (> 30 DEGREES):", is_hot)
print("COOL (<= 20 DEGREES):", is_cool)
print("EXACTLY 35 DEGREES:", is_35_degrees, "\n")

TEMPERATURES: tensor([20, 35, 19, 35, 42])
--------------------------------------------------

HOT (> 30 DEGREES): tensor([False,  True, False,  True,  True])
COOL (<= 20 DEGREES): tensor([ True, False,  True, False, False])
EXACTLY 35 DEGREES: tensor([False,  True, False,  True, False]) 



<br>

* **logical operators**: element-wise logical operations (`&` for **AND**, `|` for **OR**) on boolean tensors.

In [41]:
is_morning = torch.tensor([True, False, False, True])
is_raining = torch.tensor([False, False, True, True])
print("IS MORNING:", is_morning)
print("IS RAINING:", is_raining)
print("-" * 50)

### logical Operators (&, |)

# use '&' (AND) to find when it's both morning and raining
morning_and_raining = (is_morning & is_raining)

# use '|' (OR) to find when it's either morning or raining
morning_or_raining = is_morning | is_raining

print("\nMORNING & (AND) RAINING:", morning_and_raining)
print("MORNING | (OR) RAINING:", morning_or_raining)

IS MORNING: tensor([ True, False, False,  True])
IS RAINING: tensor([False, False,  True,  True])
--------------------------------------------------

MORNING & (AND) RAINING: tensor([False, False, False,  True])
MORNING | (OR) RAINING: tensor([ True, False,  True,  True])


### 4.3 - statistics

calculating statistics like the mean or standard deviation can be useful for understanding your dataset or for implementing certain types of normalization during the data preparation phase.

* `torch.mean()`: calculates the mean of all elements in a tensor.

In [42]:
data = torch.tensor([10.0, 20.0, 30.0, 40.0, 50.0])
print("DATA:", data)
print("-" * 45)

data_mean = data.mean()

print("\nCALCULATED MEAN:", data_mean, "\n")

DATA: tensor([10., 20., 30., 40., 50.])
---------------------------------------------

CALCULATED MEAN: tensor(30.) 



<br>

* `torch.std()`: calculates the standard deviation of all elements.

In [43]:
print("DATA:", data)
print("-" * 45)

data_std = data.std()

print("\nCALCULATED STD:", data_std, "\n")

DATA: tensor([10., 20., 30., 40., 50.])
---------------------------------------------

CALCULATED STD: tensor(15.8114) 



### 4.4 - data types:

tensor's shape is important. its data type is importsnt as well. neural networks typically perform their calculations using 32-bit floating point numbers (float32). providing data of the wrong type, such as an integer, can lead to runtime errors or unexpected behavior during training. so, it is a good practice to ensure your tensors have the correct data type for your model.

* **type casting (`.int`,`.float`, etc.)**: converts a tensor from one data type to another (e.g., from float to integer, or from one to the other).

In [45]:
print("DATA:", data)
print("DATA TYPE:", data.dtype)
print("-" * 45)

# cast the tensor to a int type
int_tensor = data.int()

print("\nCASTED DATA:", int_tensor)
print("CASTED DATA TYPE", int_tensor.dtype)

DATA: tensor([10., 20., 30., 40., 50.])
DATA TYPE: torch.float32
---------------------------------------------

CASTED DATA: tensor([10, 20, 30, 40, 50], dtype=torch.int32)
CASTED DATA TYPE torch.int32


## 5 - TENSORS EXTRA PRACTICE:

this meant to build true confidence. 

> ### how it works:
practical scenarios, from analyzing sales data to engineering new features for a machine learning model.

### PSET 1: analyzing monthly sales data

> you're a data analyst at an e-commerce company. You've been given a tensor representing the monthly sales of three different products over a period of four months. Your task is to extract meaningful insights from this data.

INFO: the tensor `sales_data` is structured as follows:

* **rows** represent the **products** (product a, product b, product c).

* **columns** represent the **months** (jan, feb, mar, apr).

**rubric**:

1. calculate the total sales for **product b** (the second row).
2. identify which months had sales **greater than 130** for **product c** (the third row) using boolean masking.
3. extract the sales data for all products for the months of **feb and mar** (the middle two columns).

<br>

<details>
<summary><span style="color:green;"><strong>solution (click here to expand)</strong></span></summary>

```python
### START CODE HERE ###

# 1. Calculate total sales for Product B.
total_sales_product_b = sales_data[1].sum()

# 2. Find months where sales for Product C were > 130.
high_sales_mask_product_c = sales_data[2] > 130

# 3. Get sales for Feb and Mar for all products.
sales_feb_mar = sales_data[:, 1:3]

### END CODE HERE ###
```

In [49]:
# sales data for 3 products over 4 months
sales_data = torch.tensor([[100, 120, 130, 110],   # product a
                           [ 90,  95, 105, 125],   # product b
                           [140, 115, 120, 150]    # product c
                          ], dtype=torch.float32)

print("ORIGINAL SALES DATA:\n\n", sales_data)
print("-" * 45)

### START CODE HERE ###

# 1. calculate total sales for product B.
total_sales_product_b = sales_data[1, :].sum()

# 2. find months where sales for product c were > 130.
high_sales_mask_product_c = sales_data[2, :] > 130

# 3. get sales for Feb and mar for all products.
sales_feb_mar = sales_data[:, 1:3]

### END CODE HERE ###

print("\nTotal Sales for Product B:                   ", total_sales_product_b)
print("\nMonths with >130 Sales for Product C (Mask): ", high_sales_mask_product_c)
print("\nSales for Feb & Mar:\n\n", sales_feb_mar)

ORIGINAL SALES DATA:

 tensor([[100., 120., 130., 110.],
        [ 90.,  95., 105., 125.],
        [140., 115., 120., 150.]])
---------------------------------------------

Total Sales for Product B:                    tensor(415.)

Months with >130 Sales for Product C (Mask):  tensor([ True, False, False,  True])

Sales for Feb & Mar:

 tensor([[120., 130.],
        [ 95., 105.],
        [115., 120.]])


#### Expected Output:

```
Total Sales for Product B:			 tensor(415.)

Months with >130 Sales for Product C (Mask):	 tensor([ True, False, False,  True])

Sales for Feb & Mar:

 tensor([[120., 130.],
        [ 95., 105.],
        [115., 120.]])
```

### PSET 2: image batch transformation

> you're working on a computer vision model and have a batch of 4 grayscale images, each of size 3x3 pixels. the data is currently in a tensor with the shape `[4, 3, 3]`, which represents `[batch_size, height, width]`.

for processing with certain deep learning frameworks, you need to transform this data into the `[batch_size, channels, height, width]` format. since the images are grayscale, **you'll need to**:

##### rubric
1. add a new dimension of size 1 at index 1 to represent the color channel.
2. after adding the channel, you realize the model expects the shape `[batch_size, height, width, channels]`. transpose the tensor to swap the channel dimension with the last dimension.

<br>

<details>
<summary><span style="color:green;"><strong>solution (click here to expand)</strong></span></summary>

```python
### START CODE HERE ###

# 1. Add a channel dimension at index 1.
image_batch_with_channel = image_batch.unsqueeze(1)

# 2. Transpose the tensor to move the channel dimension to the end.
# Swap dimension 1 (channels) with dimension 3 (the last one).
image_batch_transposed = image_batch_with_channel.transpose(1, 3)

### END CODE HERE ###
```

In [56]:
# a batch of 4 grayscale images, each 3x3
image_batch = torch.rand(4, 3, 3)

print("ORIGINAL BATCH SHAPE:", image_batch.shape)
print("-" * 45)

### START CODE HERE ###

# 1. add a channel dimension at index 1.
image_batch_with_channel = image_batch.unsqueeze(dim=1)

# 2. transpose the tensor to move the channel dimension to the end.
# swap dimension 1 (channels) with dimension 3 (the last one).
image_batch_transposed = image_batch_with_channel.transpose(1, 3)

### END CODE HERE ###


print("\nSHAPE AFTER UNSQUEEZE:", image_batch_with_channel.shape)
print("SHAPE AFTER TRANSPOSE:", image_batch_transposed.shape)

ORIGINAL BATCH SHAPE: torch.Size([4, 3, 3])
---------------------------------------------

SHAPE AFTER UNSQUEEZE: torch.Size([4, 1, 3, 3])
SHAPE AFTER TRANSPOSE: torch.Size([4, 3, 3, 1])


#### Expected Output:

```
SHAPE AFTER UNSQUEEZE: torch.Size([4, 1, 3, 3])
SHAPE AFTER TRANSPOSE: torch.Size([4, 3, 3, 1])
```

### PSET 3: combining and weighting sensor data

> you're building an environment monitoring system that uses two sensors: one for temperature and one for humidity. you receive data from these sensors as two separate 1D tensors.

**WHAT to DO**:

1. **concatenate** the two tensors into a single `2x5` tensor, where the first row is temperature data and the second is humidity data.
2. create a `weights` tensor `torch.tensor([0.6, 0.4])`.
3. use **broadcasting and element-wise multiplication** to apply these weights to the combined sensor data. the temperature data should be multiplied by 0.6 and the humidity data by 0.4.
4. fnally, calculate the **weighted average** for each time step by **summing** the weighted values along `dim=0` and **dividing** by the sum of the weights.

<br>

<details>
<summary><span style="color:green;"><strong>solution (click here to expand)</strong></span></summary>

```python
### START CODE HERE ###

# 1. Concatenate the two tensors.
# Note: You need to unsqueeze them first to stack them vertically.
combined_data = torch.cat((temperature.unsqueeze(0), humidity.unsqueeze(0)), dim=0)

# 2. Create the weights tensor.
weights = torch.tensor([0.6, 0.4])

# 3. Apply weights using broadcasting.
# You need to reshape weights to [2, 1] to broadcast across columns.
weighted_data = combined_data * weights.unsqueeze(1)

# 4. Calculate the weighted average for each time step.
#    (A true average = weighted sum / sum of weights)
weighted_sum = torch.sum(weighted_data, dim=0)
weighted_average = weighted_sum / torch.sum(weights)

### END CODE HERE ###
```

In [71]:
# sensor readings (5 time steps)
temperature = torch.tensor([22.5, 23.1, 21.9, 22.8, 23.5])
humidity = torch.tensor([55.2, 56.4, 54.8, 57.1, 56.8])

print("TEMPERATURE DATA: ", temperature)
print("HUMIDITY DATA:    ", humidity)
print("-" * 45)

### START CODE HERE ###

# 1. concatenate the two tensors.
# NOTE: you need to unsqueeze them first to stack them vertically.
combined_data = torch.cat((temperature.unsqueeze(dim=0), humidity.unsqueeze(dim=0)), dim=0)

# 2. create the weights tensor.
weights = torch.tensor([0.6, 0.4])

# 3. apply weights using broadcasting.
# You need to reshape weights to [2, 1] to broadcast across columns.
weighted_data = combined_data * weights.reshape(2, 1)

# 4. calculate the weighted average for each time step.
#    (A true average = weighted sum / sum of weights)
weighted_sum = weighted_data.sum(dim=0)
weighted_average = weighted_sum / torch.sum(weights)


### END CODE HERE ###

print("\nCOMBINED DATA (2x5):\n\n", combined_data)
print("\nWEIGHTED DATA:\n\n", weighted_data)
print("\nWEIGHTED AVERAGE:", weighted_average)

TEMPERATURE DATA:  tensor([22.5000, 23.1000, 21.9000, 22.8000, 23.5000])
HUMIDITY DATA:     tensor([55.2000, 56.4000, 54.8000, 57.1000, 56.8000])
---------------------------------------------

COMBINED DATA (2x5):

 tensor([[22.5000, 23.1000, 21.9000, 22.8000, 23.5000],
        [55.2000, 56.4000, 54.8000, 57.1000, 56.8000]])

WEIGHTED DATA:

 tensor([[13.5000, 13.8600, 13.1400, 13.6800, 14.1000],
        [22.0800, 22.5600, 21.9200, 22.8400, 22.7200]])

WEIGHTED AVERAGE: tensor([35.5800, 36.4200, 35.0600, 36.5200, 36.8200])


#### Expected Output:

```
COMBINED DATA (2x5):

 tensor([[22.5000, 23.1000, 21.9000, 22.8000, 23.5000],
        [55.2000, 56.4000, 54.8000, 57.1000, 56.8000]])

WEIGHTED DATA:

 tensor([[13.5000, 13.8600, 13.1400, 13.6800, 14.1000],
        [22.0800, 22.5600, 21.9200, 22.8400, 22.7200]])

WEIGHTED AVERAGE: tensor([35.5800, 36.4200, 35.0600, 36.5200, 36.8200])
```

### PSET 4: feature engineering for taxi fares:

> you are working with a dataset of taxi trips. you have a tensor, `trip_data`, where each row is a trip and the columns represent **[distance (km), hour_of_day (24h)]**.

#### **problem**: 
engineer a new binary feature called `is_rush_hour_long_trip`. This feature should be `True` (or `1`) only if a trip meets **both** of the following criteria:

* It's a **long trip** (distance > 10 km).
* It occurs during a **rush hour** (8-10 AM or 5-7 PM, i.e., `[8, 10)` or `[17, 19)`).

##### rubric:

1. **slice** the `trip_data` tensor to isolate the `distance` and `hour` columns.
2. use **logical and comparison operators** to create boolean masks for each condition (long trip, morning rush, evening rush).
3. combine these masks to create the final `is_rush_hour_long_trip` feature.
4. **reshape** this new 1D feature tensor into a 2D column vector and convert its data type to float so it can be combined with the original data.

<br>

<details>
<summary><span style="color:green;"><strong>solution (click here to expand)</strong></span></summary>

```python
### START CODE HERE ###

# 1. Slice the main tensor to get 1D tensors for each feature.
distances = trip_data[:, 0]
hours = trip_data[:, 1]

# 2. Create boolean masks for each condition.
is_long_trip = distances > 10.0
is_morning_rush = (hours >= 8.0) & (hours < 10.0)
is_evening_rush = (hours >= 17.0) & (hours < 19.0)

# 3. Combine masks to identify rush hour long trips.
# A trip is a rush hour long trip if it's (a morning OR evening rush) AND a long trip.
is_rush_hour_long_trip_mask = (is_morning_rush | is_evening_rush) & is_long_trip

# 4. Reshape the new feature into a column vector and cast to float.
new_feature_col = is_rush_hour_long_trip_mask.float().unsqueeze(1)

### END CODE HERE ###
```

In [76]:
# Data for 8 taxi trips: [distance, hour_of_day]
trip_data = torch.tensor([
    [5.3, 7],   # Not rush hour, not long
    [12.1, 9],  # Morning rush, long trip -> RUSH HOUR LONG
    [15.5, 13], # Not rush hour, long trip
    [6.7, 18],  # Evening rush, not long
    [2.4, 20],  # Not rush hour, not long
    [11.8, 17], # Evening rush, long trip -> RUSH HOUR LONG
    [9.0, 9],   # Morning rush, not long
    [14.2, 8]   # Morning rush, long trip -> RUSH HOUR LONG
], dtype=torch.float32)


print("ORIGINAL TRIP DATA (Distance, Hour):\n\n", trip_data)
print("-" * 55)


### START CODE HERE ###

# 1. Slice the main tensor to get 1D tensors for each feature.
distances = trip_data[:, 0]
hours = trip_data[:, 1]

# 2. Create boolean masks for each condition.
is_long_trip = distances > 10.0
is_morning_rush = (hours >= 8.0) & (hours < 10.0)
is_evening_rush = (hours >= 17.0) & (hours < 19.0)

# 3. Combine masks to identify rush hour long trips.
# A trip is a rush hour long trip if it's (a morning OR evening rush) AND a long trip.
is_rush_hour_long_trip_mask = (is_morning_rush | is_evening_rush) & is_long_trip

# 4. Reshape the new feature into a column vector and cast to float.
new_feature_col = is_rush_hour_long_trip_mask.float().unsqueeze(1)

### END CODE HERE ###

print("\n'IS RUSH HOUR LONG TRIP' MASK: ", is_rush_hour_long_trip_mask)
print("\nNEW FEATURE COLUMN (Reshaped):\n\n", new_feature_col)

# You can now concatenate this new feature to the original data
enhanced_trip_data = torch.cat((trip_data, new_feature_col), dim=1)
print("\nENHANCED DATA (with new feature at the end):\n\n", enhanced_trip_data)

ORIGINAL TRIP DATA (Distance, Hour):

 tensor([[ 5.3000,  7.0000],
        [12.1000,  9.0000],
        [15.5000, 13.0000],
        [ 6.7000, 18.0000],
        [ 2.4000, 20.0000],
        [11.8000, 17.0000],
        [ 9.0000,  9.0000],
        [14.2000,  8.0000]])
-------------------------------------------------------

'IS RUSH HOUR LONG TRIP' MASK:  tensor([False,  True, False, False, False,  True, False,  True])

NEW FEATURE COLUMN (Reshaped):

 tensor([[0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.]])

ENHANCED DATA (with new feature at the end):

 tensor([[ 5.3000,  7.0000,  0.0000],
        [12.1000,  9.0000,  1.0000],
        [15.5000, 13.0000,  0.0000],
        [ 6.7000, 18.0000,  0.0000],
        [ 2.4000, 20.0000,  0.0000],
        [11.8000, 17.0000,  1.0000],
        [ 9.0000,  9.0000,  0.0000],
        [14.2000,  8.0000,  1.0000]])


#### Expected Output:

```
'IS RUSH HOUR LONG TRIP' MASK:  tensor([False,  True, False, False, False,  True, False,  True])

NEW FEATURE COLUMN (Reshaped):

 tensor([[0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.]])

ENHANCED DATA (with new feature at the end):

 tensor([[ 5.3000,  7.0000,  0.0000],
        [12.1000,  9.0000,  1.0000],
        [15.5000, 13.0000,  0.0000],
        [ 6.7000, 18.0000,  0.0000],
        [ 2.4000, 20.0000,  0.0000],
        [11.8000, 17.0000,  1.0000],
        [ 9.0000,  9.0000,  0.0000],
        [14.2000,  8.0000,  1.0000]])
```        

## wraps:

the element-wise arithmetic and broadcasting you practiced are precisely how a neural network efficiently applies weights and biases to entire batches of data at once. the reshaping techniques like `unsqueeze` and `squeeze` are what allow you to prepare a single data point for a model that expects a batch, and then clean up the output afterward. these are not just abstract exercises; they are the day-to-day operations required to build and debug effective deep learning models.
